### ISSUE TITLE
Create a simple guildine

### ISSUE THREAD

**Issue by Badger0909** [Badger0909/Hacktoberfest-2024#1]
Create a simple guidline in the README.md, explaining the rules of Hacktoberfest and some general rules.

**Comment by NagaJahnaviD** [comment]
hey @Badger0909 could you assign me this issue?

**Comment by Badger0909** [comment]
Done, If you make a pull request i'll try to merge it at a reasonable time

**Comment by NagaJahnaviD** [comment]
@Badger0909 , seems like you have sorted the issue.
Do tell me if I could add anything else.

**Comment by Badger0909** [comment]
@NagaJahnaviD, there is still some parts I want to implement such as new individual folders for each coding language like python, java, and C++, if you can add a contributor list as well that should be good but feel free to pull request any improvements so I can merge.

**Comment by NagaJahnaviD** [comment]
@Badger0909  Okay!
