### ISSUE TITLE
Simple Calculator

### ISSUE THREAD

**Issue by Badger0909** [Badger0909/Hacktoberfest-2024#11]
Make a calculator that can be used for anything (graphing, arithmetic, BMI)

**Comment by hriteshMaikap** [comment]
Hey! I would be interested in this. Can you elaborate more on the requirements and the libraries restrictions (if any).

**Comment by aniruddhaadak80** [comment]
I am working on this . Assign me please .

**Comment by aniruddhaadak80** [comment]
I have done this #13

**Comment by Badger0909** [comment]
Of course, you should use python, feel free to import / use any libraries
