### ISSUE TITLE
RPS game in Java

### ISSUE THREAD

**Issue by Badger0909** [Badger0909/Hacktoberfest-2024#21]
Create a new folder called Java, inside it enter your code and submit a pull request. The code should include a Rock Paper Scissors game.

**Comment by singhal-amit** [comment]
Hi @Badger0909, Is this issue completed? if not can you assign this to me under the labels `hacktoberfest` & `hacktoberfest-accepted`

**Comment by aniruddhaadak80** [comment]
Assign this to me . I am working on this .
